// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cedukqaxrvtakgtazxhv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNlZHVrcWF4cnZ0YWtndGF6eGh2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMxNjkzNzksImV4cCI6MjA1ODc0NTM3OX0.Am9IQ9BM6grtxU0kZCHYQ3v_PqIhLu7b82omPGmhgUE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);